name: Conditional PR comment
description:
  GitHub Action that supports instructing the author of a Pull Request (PR) how
  to resolve a given problem within the context of a PR. Conditionally adds a
  comment to the PR with resolution instructions, and once the condition is
  found to be resolved, allows the previously added comment, if one exists at
  that time, to be removed from the PR.
inputs:
  instruction-text:
    required: true
    description:
      This is the full text of the message to be placed within a comment of the
      given PR to instruct the author of the PR how to resolve a given problem.
  instruction-text-detector:
    required: true
    description:
      This is some unique verbatim subset of the instruction-text that is to be
      used to determine if a comment has already been created against the PR
      that instructs the author how to resolve the given problem.
  delete-comment-on-resolution:
    required: true
    description:
      Whether or not to delete the comment that has been added to the PR upon
      problem resolution.
    default: "true"
  github-token:
    required: true
    description:
      GitHub token that can create/delete comments. e.g. 'secrets.GITHUB_TOKEN'
runs:
  using: composite
  steps:
    - name:
        Check to see if problem resolution instructions comment already present
        on the PR
      uses: peter-evans/find-comment@v2
      if: github.event_name == 'pull_request'
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: ${{ inputs.instruction-text-detector }}
    - name: Conditionally create instructions comment for PR author
      if:
        github.event_name == 'pull_request' && failure() &&
        steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ inputs.instruction-text}}
    - name: Delete instructions comment from PR if problem has been resolved
      if:
        inputs.delete-comment-on-resolution == 'true' && github.event_name ==
        'pull_request' && success() && steps.fc.outputs.comment-id != ''
      uses: jungwinter/comment@v1
      with:
        type: delete
        comment_id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ inputs.github-token }}
