name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v1

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Introduce problem to resolve
        run: echo 'fixme' > ./badshell.sh
      - name: Create temporary pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Temp PR for unit testing purposes
          base: main
          branch-suffix: timestamp
          token: ${{ secrets.OPEN_TURO_GITHUB_TOKEN }}
          draft: true
      - name: Cleanup temporary pull request
        if: always()
        uses: peter-evans/close-pull@v2
        with:
          id: ${{ steps.cpr.outputs.pull-request-number }}
          comment: Auto-closing temporary PR
          delete-branch: true
